### PR TITLE
Integration of ListBox extended :

### PR DESCRIPTION
**Pull request by FBoissadier**
- Add styling property (itemMarginExt) : Add the possibility to add margin on items in the list
- Add new event (ItemClickExt) : Triggered when you click on a item and return :
        - clickedValue (String) : Value of the item clicked
        - clickedText (String) : Text of the item clicked
        - clickedIndex (UInteger): Index of the item clicked

Why this extension of the ListBox widget ?

For the styling property (itemMarginExt), it's just for styling and create space between items in the list.

I had a case in a project to display list of equipement in a ListBox, using Value as the index in an array of the equipement and Text is the name of the equipement.

I cannot used event SelectedIndexChanged, because if you try to click on first item and default value of selectedIndex is 0 then SelectedIndexChanged didn't fired.

I didn't know how to create documentation with mkdoc, if you need I can create markdown files.

This widget was developed and tested using MappView 5.24.1 and AS 4.9.5.36

### CODE REVIEW

**Comment by FBoissadier** [comment]
I've update my code to follow guideline.
I've check about mkdocs and create the documentation page for the listbox widget

**Comment by stephan1827** [comment]
Thank you for contributing to this repository. I am out of the office this week, but I will take a look at the PR next week.

**Comment by FBoissadier** [comment]
No problem, don't hesitate if I forgot something in the PR !

**Comment by stephan1827** [comment]
Thx again for sharing this

**Pull request merged**
